PATH_ROOT = "./"
DATA_PATH = "data/"
POSITIVE_DICTIONARY_NAME = "positive_dictionary.txt"
NEGATIVE_DICTIONARY_NAME = "negative_dictionary.txt"
FILE_TEXT_NAME = "text.txt"
LOG_PATH = "logs/"
PROPERTIES_PATH = "database/database.properties"
